baseURL = ""
languageCode = "zh-Hans"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "Edward Kerman 的随笔"
    signature = "Chemistry fucks me everyday!"
    cover = ""

    name = "Edward Kerman"
    avatar = "/img/default_avatar.png"

[module]
[[module.imports]]
  path = "hugo-mod-twemoji"
